Repository GraphicEditStudio/LD53, pull requests merged in 2023-04, with the labels that each got.

#5 Circle and Triangle
  LD53/Assets/Scenes/SampleScene.unity
Labels: design

#7 CameraPrefabSetings
  LD53/Assets/Prefabs/Circle.prefab
  LD53/Assets/Prefabs/Circle.prefab.meta
  LD53/Assets/Prefabs/Directional Light.prefab
  LD53/Assets/Prefabs/Directional Light.prefab.meta
  LD53/Assets/Prefabs/Main Camera.prefab
  LD53/Assets/Prefabs/Main Camera.prefab.meta
  LD53/Assets/Prefabs/Point Light.prefab
  LD53/Assets/Prefabs/Point Light.prefab.meta
  LD53/Assets/Prefabs/Triangle.prefab
  LD53/Assets/Prefabs/Triangle.prefab.meta
  LD53/Assets/Scenes/SampleScene.unity
Labels: bug

#9 Update method is changed
  LD53/Assets/Code/test.cs
Labels: code

#43 Working tests
  LD53/Assets/Art/sogan-adem-A.png
  LD53/Assets/Art/sogan-adem-A.png.meta
  LD53/Assets/Code/BacktoMenu.cs
  LD53/Assets/Code/BacktoMenu.cs.meta
  LD53/Assets/Prefabs/Player.prefab
  LD53/Assets/Scenes/Credits_Scene.unity
  LD53/Assets/Scenes/Credits_Scene/CreditsCamera.prefab
  LD53/Assets/Scenes/Credits_Scene/CreditsCanvas.prefab
  LD53/Assets/Scenes/Menu_Start.unity
  LD53/Assets/Scenes/Menu_Start/MenuStart Canvas.prefab
  LD53/Assets/Scenes/Menu_Start/MenuStart EventSystem.prefab
  LD53/Assets/Scenes/Menu_Start/MenuStart EventSystem.prefab.meta
Labels: bug

#46 tets Y
  LD53/Assets/Code/test.cs
Labels: animation

#52 Art
  LD53/Assets/Art/BossDog.psb
  LD53/Assets/Art/BossFat.psb
  LD53/Assets/Art/Boxes.psb
  LD53/Assets/Art/Export Images/BossDog.jpg
  LD53/Assets/Art/Export Images/BossDog.png
Labels: art

#59 cam setup
  LD53/Assets/Art/EnvironmentCity.psb.meta
  LD53/Assets/Art/EnvironmentDesert.psb.meta
  LD53/Assets/Art/EnvironmentJunkyard.psb.meta
  LD53/Assets/Art/GameOver.psb.meta
  LD53/Assets/Prefabs/Environment.prefab
  LD53/Assets/Scenes/Main_Scene.unity
  LD53/ProjectSettings/TagManager.asset
Labels: animation
